#!/bin/sh -e

cmd=$1
shift

AM_VERSION=-1.7

case "$cmd" in
  get-version)
        head -1 debian/changelog | sed -e 's/.*(\([^)]*\)).*/\1/'
    ;;
  build-exclude-list|dist-exclude-list|prepare-dist)
    ## These lists can be used to delegate build-time and dist-time exclude lists
    ## For example (syslog-ng-agent):
    ##
    ##    echo "out obj *.aqt *.ncb *.suo *.vcproj.*.user"
    ##
    ;;
  bootstrap)
    ;;
  configure)
    ./configure  --enable-utf8 --enable-unicode-properties $@
    ;;
  make)
    make $@
    ;;
  *)
    echo "Unknown command: $cmd"
    exit 1
    ;;
esac
exit 0
